In [2]:
import pandas as pd
%matplotlib inline

In [3]:
df_BABA = pd.read_csv("./data/BABA历史数据.csv")
df_BABA["公司"]="BABA"
df_BIDU = pd.read_csv("./data/BIDU历史数据.csv")
df_BIDU["公司"]="BIDU"
df_JD = pd.read_csv("./data/JD历史数据.csv")
df_JD["公司"]="JD"
df_PDD = pd.read_csv("./data/PDD历史数据.csv")
df_PDD["公司"]="PDD"

In [4]:
df = pd.concat([df_BABA, df_BIDU, df_JD, df_PDD])

In [5]:
df

           日期     收盘     开盘      高      低     交易量     涨跌幅    公司
0   2023-4-28  84.69  84.18  85.08  83.87  18.11M   0.26%  BABA
1   2023-4-27  84.47  83.07  84.64  82.64  20.93M   1.99%  BABA
2   2023-4-26  82.82  85.04  85.22  82.76  24.98M  -0.12%  BABA
3   2023-4-25  82.92  85.32  85.70  82.21  34.25M  -4.57%  BABA
4   2023-4-24  86.89  88.40  88.48  86.04  22.71M  -2.51%  BABA
..        ...    ...    ...    ...    ...     ...     ...   ...
14  2023-4-10  71.31  71.00  72.00  70.18   4.82M  -1.00%   PDD
15   2023-4-6  72.03  72.50  72.60  71.16   5.12M  -0.40%   PDD
16   2023-4-5  72.32  73.14  73.14  71.62   5.24M  -1.20%   PDD
17   2023-4-4  73.20  74.90  74.90  72.79   5.00M  -2.19%   PDD
18   2023-4-3  74.84  74.07  74.89  72.20   7.27M  -1.40%   PDD

[76 rows x 8 columns]

In [6]:
df_PDD

           日期     收盘     开盘      高      低     交易量     涨跌幅   公司
0   2023-4-28  68.15  65.40  68.81  65.40   6.02M   3.07%  PDD
1   2023-4-27  66.12  66.10  66.68  64.58   5.31M   1.49%  PDD
2   2023-4-26  65.15  66.29  66.84  64.62   6.76M   0.88%  PDD
3   2023-4-25  64.58  64.45  65.23  63.58   8.93M  -3.25%  PDD
4   2023-4-24  66.75  68.75  68.75  65.33   8.83M  -3.58%  PDD
5   2023-4-21  69.23  68.61  69.23  67.86   6.56M  -0.66%  PDD
6   2023-4-20  69.69  69.74  70.20  68.89   7.40M  -0.57%  PDD
7   2023-4-19  70.09  68.60  70.17  68.50   3.77M  -0.24%  PDD
8   2023-4-18  70.26  69.76  71.98  69.75   5.76M   1.90%  PDD
9   2023-4-17  68.95  69.34  69.52  68.08   6.56M   1.88%  PDD
10  2023-4-14  67.68  68.50  68.85  67.45   5.13M  -1.24%  PDD
11  2023-4-13  68.53  68.03  69.53  67.83   7.08M   2.25%  PDD
12  2023-4-12  67.02  69.16  69.69  66.74  14.86M  -5.22%  PDD
13  2023-4-11  70.71  72.05  72.44  70.62   5.68M  -0.84%  PDD
14  2023-4-10  71.31  71.00  72.00  70.18   4.82M  -1.00%  PDD
15   2023-4-6  72.03  72.50  72.60  71.16   5.12M  -0.40%  PDD
16   2023-4-5  72.32  73.14  73.14  71.62   5.24M  -1.20%  PDD
17   2023-4-4  73.20  74.90  74.90  72.79   5.00M  -2.19%  PDD
18   2023-4-3  74.84  74.07  74.89  72.20   7.27M  -1.40%  PDD

In [7]:
df.shape

(76, 8)

In [8]:
df.head(3)

          日期     收盘     开盘      高      低     交易量     涨跌幅    公司
0  2023-4-28  84.69  84.18  85.08  83.87  18.11M   0.26%  BABA
1  2023-4-27  84.47  83.07  84.64  82.64  20.93M   1.99%  BABA
2  2023-4-26  82.82  85.04  85.22  82.76  24.98M  -0.12%  BABA

In [9]:
df["公司"].unique()

array(['BABA', 'BIDU', 'JD', 'PDD'], dtype=object)

In [10]:
df.index

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
            15, 16, 17, 18,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,
            13, 14, 15, 16, 17, 18,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
            11, 12, 13, 14, 15, 16, 17, 18],
           dtype='int64')

In [11]:
df.groupby("公司")["收盘"].mean()

公司
BABA     93.332632
BIDU    131.570000
JD       37.605789
PDD      69.295263
Name: 收盘, dtype: float64

In [12]:
ser = df.groupby(["公司", "日期"])["收盘"].mean()
ser

公司    日期
BABA  2023-4-10    101.54
      2023-4-11     99.76
      2023-4-12     93.84
      2023-4-13     96.17
      2023-4-14     94.55
                    ...
PDD   2023-4-28     68.15
      2023-4-3      74.84
      2023-4-4      73.20
      2023-4-5      72.32
      2023-4-6      72.03
Name: 收盘, Length: 76, dtype: float64

In [13]:
ser.index

MultiIndex([('BABA', '2023-4-10'),
            ('BABA', '2023-4-11'),
            ('BABA', '2023-4-12'),
            ('BABA', '2023-4-13'),
            ('BABA', '2023-4-14'),
            ('BABA', '2023-4-17'),
            ('BABA', '2023-4-18'),
            ('BABA', '2023-4-19'),
            ('BABA', '2023-4-20'),
            ('BABA', '2023-4-21'),
            ('BABA', '2023-4-24'),
            ('BABA', '2023-4-25'),
            ('BABA', '2023-4-26'),
            ('BABA', '2023-4-27'),
            ('BABA', '2023-4-28'),
            ('BABA',  '2023-4-3'),
            ('BABA',  '2023-4-4'),
            ('BABA',  '2023-4-5'),
            ('BABA',  '2023-4-6'),
            ('BIDU', '2023-4-10'),
            ('BIDU', '2023-4-11'),
            ('BIDU', '2023-4-12'),
            ('BIDU', '2023-4-13'),
            ('BIDU', '2023-4-14'),
            ('BIDU', '2023-4-17'),
            ('BIDU', '2023-4-18'),
            ('BIDU', '2023-4-19'),
            ('BIDU', '2023-4-20'),
            ('BIDU', '2023-4-21'),
            ('BIDU', '2023-4-24'),
            ('BIDU', '2023-4-25'),
            ('BIDU', '2023-4-26'),
            ('BIDU', '2023-4-27'),
            ('BIDU', '2023-4-28'),
            ('BIDU',  '2023-4-3'),
            ('BIDU',  '2023-4-4'),
            ('BIDU',  '2023-4-5'),
            ('BIDU',  '2023-4-6'),
            (  'JD', '2023-4-10'),
            (  'JD', '2023-4-11'),
            (  'JD', '2023-4-12'),
            (  'JD', '2023-4-13'),
            (  'JD', '2023-4-14'),
            (  'JD', '2023-4-17'),
            (  'JD', '2023-4-18'),
            (  'JD', '2023-4-19'),
            (  'JD', '2023-4-20'),
            (  'JD', '2023-4-21'),
            (  'JD', '2023-4-24'),
            (  'JD', '2023-4-25'),
            (  'JD', '2023-4-26'),
            (  'JD', '2023-4-27'),
            (  'JD', '2023-4-28'),
            (  'JD',  '2023-4-3'),
            (  'JD',  '2023-4-4'),
            (  'JD',  '2023-4-5'),
            (  'JD',  '2023-4-6'),
            ( 'PDD', '2023-4-10'),
            ( 'PDD', '2023-4-11'),
            ( 'PDD', '2023-4-12'),
            ( 'PDD', '2023-4-13'),
            ( 'PDD', '2023-4-14'),
            ( 'PDD', '2023-4-17'),
            ( 'PDD', '2023-4-18'),
            ( 'PDD', '2023-4-19'),
            ( 'PDD', '2023-4-20'),
            ( 'PDD', '2023-4-21'),
            ( 'PDD', '2023-4-24'),
            ( 'PDD', '2023-4-25'),
            ( 'PDD', '2023-4-26'),
            ( 'PDD', '2023-4-27'),
            ( 'PDD', '2023-4-28'),
            ( 'PDD',  '2023-4-3'),
            ( 'PDD',  '2023-4-4'),
            ( 'PDD',  '2023-4-5'),
            ( 'PDD',  '2023-4-6')],
           names=['公司', '日期'])

In [14]:
ser.unstack()

日期,2023-4-10,2023-4-11,2023-4-12,2023-4-13,2023-4-14,2023-4-17,2023-4-18,2023-4-19,2023-4-20,2023-4-21,2023-4-24,2023-4-25,2023-4-26,2023-4-27,2023-4-28,2023-4-3,2023-4-4,2023-4-5,2023-4-6
公司,,,,,,,,,,,,,,,,,,,
BABA,101.54,99.76,93.84,96.17,94.55,96.42,95.49,93.49,90.74,89.13,86.89,82.92,82.82,84.47,84.69,98.39,100.72,98.55,102.74
BIDU,139.00,136.69,136.40,132.73,128.75,131.54,131.18,128.15,127.44,124.96,122.62,116.94,117.07,118.46,120.61,149.19,148.57,144.54,144.99
JD,39.97,40.01,36.95,37.45,36.85,38.05,37.73,37.10,36.19,35.63,34.68,33.70,34.23,34.75,35.72,42.40,41.84,40.50,40.76
PDD,71.31,70.71,67.02,68.53,67.68,68.95,70.26,70.09,69.69,69.23,66.75,64.58,65.15,66.12,68.15,74.84,73.20,72.32,72.03

In [15]:
ser

公司    日期
BABA  2023-4-10    101.54
      2023-4-11     99.76
      2023-4-12     93.84
      2023-4-13     96.17
      2023-4-14     94.55
                    ...
PDD   2023-4-28     68.15
      2023-4-3      74.84
      2023-4-4      73.20
      2023-4-5      72.32
      2023-4-6      72.03
Name: 收盘, Length: 76, dtype: float64

In [16]:
ser.reset_index()

      公司         日期      收盘
0   BABA  2023-4-10  101.54
1   BABA  2023-4-11   99.76
2   BABA  2023-4-12   93.84
3   BABA  2023-4-13   96.17
4   BABA  2023-4-14   94.55
..   ...        ...     ...
71   PDD  2023-4-28   68.15
72   PDD   2023-4-3   74.84
73   PDD   2023-4-4   73.20
74   PDD   2023-4-5   72.32
75   PDD   2023-4-6   72.03

[76 rows x 3 columns]

In [17]:
ser

公司    日期
BABA  2023-4-10    101.54
      2023-4-11     99.76
      2023-4-12     93.84
      2023-4-13     96.17
      2023-4-14     94.55
                    ...
PDD   2023-4-28     68.15
      2023-4-3      74.84
      2023-4-4      73.20
      2023-4-5      72.32
      2023-4-6      72.03
Name: 收盘, Length: 76, dtype: float64

In [18]:
ser.loc["BIDU"]

日期
2023-4-10    139.00
2023-4-11    136.69
2023-4-12    136.40
2023-4-13    132.73
2023-4-14    128.75
2023-4-17    131.54
2023-4-18    131.18
2023-4-19    128.15
2023-4-20    127.44
2023-4-21    124.96
2023-4-24    122.62
2023-4-25    116.94
2023-4-26    117.07
2023-4-27    118.46
2023-4-28    120.61
2023-4-3     149.19
2023-4-4     148.57
2023-4-5     144.54
2023-4-6     144.99
Name: 收盘, dtype: float64

In [19]:
ser.loc[("BIDU", "2023-4-26")]

117.07

In [20]:
ser.loc[:, '2023-4-26']

公司
BABA     82.82
BIDU    117.07
JD       34.23
PDD      65.15
Name: 收盘, dtype: float64

In [21]:
df.set_index(["公司", "日期"], inplace=True)
df

                   收盘     开盘      高      低     交易量     涨跌幅
公司   日期
BABA 2023-4-28  84.69  84.18  85.08  83.87  18.11M   0.26%
     2023-4-27  84.47  83.07  84.64  82.64  20.93M   1.99%
     2023-4-26  82.82  85.04  85.22  82.76  24.98M  -0.12%
     2023-4-25  82.92  85.32  85.70  82.21  34.25M  -4.57%
     2023-4-24  86.89  88.40  88.48  86.04  22.71M  -2.51%
...               ...    ...    ...    ...     ...     ...
PDD  2023-4-10  71.31  71.00  72.00  70.18   4.82M  -1.00%
     2023-4-6   72.03  72.50  72.60  71.16   5.12M  -0.40%
     2023-4-5   72.32  73.14  73.14  71.62   5.24M  -1.20%
     2023-4-4   73.20  74.90  74.90  72.79   5.00M  -2.19%
     2023-4-3   74.84  74.07  74.89  72.20   7.27M  -1.40%

[76 rows x 6 columns]

In [22]:
df.index

MultiIndex([('BABA', '2023-4-28'),
            ('BABA', '2023-4-27'),
            ('BABA', '2023-4-26'),
            ('BABA', '2023-4-25'),
            ('BABA', '2023-4-24'),
            ('BABA', '2023-4-21'),
            ('BABA', '2023-4-20'),
            ('BABA', '2023-4-19'),
            ('BABA', '2023-4-18'),
            ('BABA', '2023-4-17'),
            ('BABA', '2023-4-14'),
            ('BABA', '2023-4-13'),
            ('BABA', '2023-4-12'),
            ('BABA', '2023-4-11'),
            ('BABA', '2023-4-10'),
            ('BABA',  '2023-4-6'),
            ('BABA',  '2023-4-5'),
            ('BABA',  '2023-4-4'),
            ('BABA',  '2023-4-3'),
            ('BIDU', '2023-4-28'),
            ('BIDU', '2023-4-27'),
            ('BIDU', '2023-4-26'),
            ('BIDU', '2023-4-25'),
            ('BIDU', '2023-4-24'),
            ('BIDU', '2023-4-21'),
            ('BIDU', '2023-4-20'),
            ('BIDU', '2023-4-19'),
            ('BIDU', '2023-4-18'),
            ('BIDU', '2023-4-17'),
            ('BIDU', '2023-4-14'),
            ('BIDU', '2023-4-13'),
            ('BIDU', '2023-4-12'),
            ('BIDU', '2023-4-11'),
            ('BIDU', '2023-4-10'),
            ('BIDU',  '2023-4-6'),
            ('BIDU',  '2023-4-5'),
            ('BIDU',  '2023-4-4'),
            ('BIDU',  '2023-4-3'),
            (  'JD', '2023-4-28'),
            (  'JD', '2023-4-27'),
            (  'JD', '2023-4-26'),
            (  'JD', '2023-4-25'),
            (  'JD', '2023-4-24'),
            (  'JD', '2023-4-21'),
            (  'JD', '2023-4-20'),
            (  'JD', '2023-4-19'),
            (  'JD', '2023-4-18'),
            (  'JD', '2023-4-17'),
            (  'JD', '2023-4-14'),
            (  'JD', '2023-4-13'),
            (  'JD', '2023-4-12'),
            (  'JD', '2023-4-11'),
            (  'JD', '2023-4-10'),
            (  'JD',  '2023-4-6'),
            (  'JD',  '2023-4-5'),
            (  'JD',  '2023-4-4'),
            (  'JD',  '2023-4-3'),
            ( 'PDD', '2023-4-28'),
            ( 'PDD', '2023-4-27'),
            ( 'PDD', '2023-4-26'),
            ( 'PDD', '2023-4-25'),
            ( 'PDD', '2023-4-24'),
            ( 'PDD', '2023-4-21'),
            ( 'PDD', '2023-4-20'),
            ( 'PDD', '2023-4-19'),
            ( 'PDD', '2023-4-18'),
            ( 'PDD', '2023-4-17'),
            ( 'PDD', '2023-4-14'),
            ( 'PDD', '2023-4-13'),
            ( 'PDD', '2023-4-12'),
            ( 'PDD', '2023-4-11'),
            ( 'PDD', '2023-4-10'),
            ( 'PDD',  '2023-4-6'),
            ( 'PDD',  '2023-4-5'),
            ( 'PDD',  '2023-4-4'),
            ( 'PDD',  '2023-4-3')],
           names=['公司', '日期'])

In [23]:
df.sort_index(inplace=True) 
df

                    收盘      开盘       高       低     交易量     涨跌幅
公司   日期
BABA 2023-4-10  101.54  100.62  102.83  100.59  16.26M  -1.17%
     2023-4-11   99.76  102.46  102.54   99.20  18.10M  -1.75%
     2023-4-12   93.84   97.82   98.89   93.58  33.81M  -5.93%
     2023-4-13   96.17   95.88   97.19   95.10  23.22M   2.48%
     2023-4-14   94.55   95.63   96.12   93.84  14.10M  -1.68%
...                ...     ...     ...     ...     ...     ...
PDD  2023-4-28   68.15   65.40   68.81   65.40   6.02M   3.07%
     2023-4-3    74.84   74.07   74.89   72.20   7.27M  -1.40%
     2023-4-4    73.20   74.90   74.90   72.79   5.00M  -2.19%
     2023-4-5    72.32   73.14   73.14   71.62   5.24M  -1.20%
     2023-4-6    72.03   72.50   72.60   71.16   5.12M  -0.40%

[76 rows x 6 columns]

In [24]:
df.loc["BIDU"]

               收盘      开盘       高       低    交易量     涨跌幅
日期
2023-4-10  139.00  140.44  140.63  137.86  3.03M  -4.13%
2023-4-11  136.69  139.89  140.18  136.32  2.50M  -1.66%
2023-4-12  136.40  136.14  138.18  135.95  3.22M  -0.21%
2023-4-13  132.73  136.58  136.64  132.45  3.41M  -2.69%
2023-4-14  128.75  131.46  131.46  127.75  3.36M  -3.00%
2023-4-17  131.54  131.86  132.07  130.03  2.57M   2.17%
2023-4-18  131.18  131.95  132.58  130.20  1.98M  -0.27%
2023-4-19  128.15  128.08  129.19  127.58  1.73M  -2.31%
2023-4-20  127.44  128.00  129.64  126.26  2.82M  -0.55%
2023-4-21  124.96  125.72  126.83  124.36  1.79M  -1.95%
2023-4-24  122.62  123.60  123.68  122.10  1.99M  -1.87%
2023-4-25  116.94  119.63  120.20  116.52  3.65M  -4.63%
2023-4-26  117.07  120.45  120.50  117.02  2.34M   0.11%
2023-4-27  118.46  117.11  118.94  116.37  1.96M   1.19%
2023-4-28  120.61  118.00  121.26  117.40  1.85M   1.81%
2023-4-3   149.19  150.00  151.09  148.53  1.79M  -1.15%
2023-4-4   148.57  149.59  151.03  146.74  2.23M  -0.42%
2023-4-5   144.54  148.14  148.14  142.65  2.19M  -2.71%
2023-4-6   144.99  144.64  146.27  144.03  1.55M   0.31%

In [25]:
df.loc[("BIDU", "2023-4-26")]

收盘     117.07
开盘     120.45
高       120.5
低      117.02
交易量     2.34M
涨跌幅     0.11%
Name: (BIDU, 2023-4-26), dtype: object

In [26]:
df.loc[("BIDU", "2023-4-26"), '开盘']

120.45

In [27]:
df.loc[["BIDU", "JD"]]

                    收盘      开盘       高       低     交易量     涨跌幅
公司   日期
BIDU 2023-4-10  139.00  140.44  140.63  137.86   3.03M  -4.13%
     2023-4-11  136.69  139.89  140.18  136.32   2.50M  -1.66%
     2023-4-12  136.40  136.14  138.18  135.95   3.22M  -0.21%
     2023-4-13  132.73  136.58  136.64  132.45   3.41M  -2.69%
     2023-4-14  128.75  131.46  131.46  127.75   3.36M  -3.00%
     2023-4-17  131.54  131.86  132.07  130.03   2.57M   2.17%
     2023-4-18  131.18  131.95  132.58  130.20   1.98M  -0.27%
     2023-4-19  128.15  128.08  129.19  127.58   1.73M  -2.31%
     2023-4-20  127.44  128.00  129.64  126.26   2.82M  -0.55%
     2023-4-21  124.96  125.72  126.83  124.36   1.79M  -1.95%
     2023-4-24  122.62  123.60  123.68  122.10   1.99M  -1.87%
     2023-4-25  116.94  119.63  120.20  116.52   3.65M  -4.63%
     2023-4-26  117.07  120.45  120.50  117.02   2.34M   0.11%
     2023-4-27  118.46  117.11  118.94  116.37   1.96M   1.19%
     2023-4-28  120.61  118.00  121.26  117.40   1.85M   1.81%
     2023-4-3   149.19  150.00  151.09  148.53   1.79M  -1.15%
     2023-4-4   148.57  149.59  151.03  146.74   2.23M  -0.42%
     2023-4-5   144.54  148.14  148.14  142.65   2.19M  -2.71%
     2023-4-6   144.99  144.64  146.27  144.03   1.55M   0.31%
JD   2023-4-10   39.97   39.38   39.97   39.05   7.72M  -1.94%
     2023-4-11   40.01   40.54   40.75   39.96   8.78M   0.10%
     2023-4-12   36.95   39.01   39.19   36.87  22.57M  -7.65%
     2023-4-13   37.45   37.67   37.73   37.05  12.79M   1.35%
     2023-4-14   36.85   37.30   37.55   36.45  10.71M  -1.60%
     2023-4-17   38.05   37.86   38.17   37.55  10.14M   3.26%
     2023-4-18   37.73   38.30   38.42   37.53   8.52M  -0.84%
     2023-4-19   37.10   36.82   37.14   36.66   7.56M  -1.67%
     2023-4-20   36.19   36.46   36.76   35.97  12.62M  -2.45%
     2023-4-21   35.63   35.40   35.74   35.22  10.12M  -1.55%
     2023-4-24   34.68   35.29   35.34   34.16  15.12M  -2.67%
     2023-4-25   33.70   33.86   34.26   33.53  11.82M  -2.83%
     2023-4-26   34.23   34.96   35.15   34.13   8.54M   1.57%
     2023-4-27   34.75   34.33   34.82   34.03   7.53M   1.52%
     2023-4-28   35.72   34.68   35.86   34.61   8.65M   2.79%
     2023-4-3    42.40   43.27   43.56   41.96  12.79M  -3.39%
     2023-4-4    41.84   42.13   42.44   41.42   8.55M  -1.32%
     2023-4-5    40.50   41.14   41.21   40.09   7.47M  -3.20%
     2023-4-6    40.76   40.50   40.92   39.85   7.17M   0.64%

In [28]:
df.loc[["BIDU", "PDD", ""], :]

                    收盘      开盘       高       低     交易量     涨跌幅
公司   日期
BIDU 2023-4-10  139.00  140.44  140.63  137.86   3.03M  -4.13%
     2023-4-11  136.69  139.89  140.18  136.32   2.50M  -1.66%
     2023-4-12  136.40  136.14  138.18  135.95   3.22M  -0.21%
     2023-4-13  132.73  136.58  136.64  132.45   3.41M  -2.69%
     2023-4-14  128.75  131.46  131.46  127.75   3.36M  -3.00%
     2023-4-17  131.54  131.86  132.07  130.03   2.57M   2.17%
     2023-4-18  131.18  131.95  132.58  130.20   1.98M  -0.27%
     2023-4-19  128.15  128.08  129.19  127.58   1.73M  -2.31%
     2023-4-20  127.44  128.00  129.64  126.26   2.82M  -0.55%
     2023-4-21  124.96  125.72  126.83  124.36   1.79M  -1.95%
     2023-4-24  122.62  123.60  123.68  122.10   1.99M  -1.87%
     2023-4-25  116.94  119.63  120.20  116.52   3.65M  -4.63%
     2023-4-26  117.07  120.45  120.50  117.02   2.34M   0.11%
     2023-4-27  118.46  117.11  118.94  116.37   1.96M   1.19%
     2023-4-28  120.61  118.00  121.26  117.40   1.85M   1.81%
     2023-4-3   149.19  150.00  151.09  148.53   1.79M  -1.15%
     2023-4-4   148.57  149.59  151.03  146.74   2.23M  -0.42%
     2023-4-5   144.54  148.14  148.14  142.65   2.19M  -2.71%
     2023-4-6   144.99  144.64  146.27  144.03   1.55M   0.31%
PDD  2023-4-10   71.31   71.00   72.00   70.18   4.82M  -1.00%
     2023-4-11   70.71   72.05   72.44   70.62   5.68M  -0.84%
     2023-4-12   67.02   69.16   69.69   66.74  14.86M  -5.22%
     2023-4-13   68.53   68.03   69.53   67.83   7.08M   2.25%
     2023-4-14   67.68   68.50   68.85   67.45   5.13M  -1.24%
     2023-4-17   68.95   69.34   69.52   68.08   6.56M   1.88%
     2023-4-18   70.26   69.76   71.98   69.75   5.76M   1.90%
     2023-4-19   70.09   68.60   70.17   68.50   3.77M  -0.24%
     2023-4-20   69.69   69.74   70.20   68.89   7.40M  -0.57%
     2023-4-21   69.23   68.61   69.23   67.86   6.56M  -0.66%
     2023-4-24   66.75   68.75   68.75   65.33   8.83M  -3.58%
     2023-4-25   64.58   64.45   65.23   63.58   8.93M  -3.25%
     2023-4-26   65.15   66.29   66.84   64.62   6.76M   0.88%
     2023-4-27   66.12   66.10   66.68   64.58   5.31M   1.49%
     2023-4-28   68.15   65.40   68.81   65.40   6.02M   3.07%
     2023-4-3    74.84   74.07   74.89   72.20   7.27M  -1.40%
     2023-4-4    73.20   74.90   74.90   72.79   5.00M  -2.19%
     2023-4-5    72.32   73.14   73.14   71.62   5.24M  -1.20%
     2023-4-6    72.03   72.50   72.60   71.16   5.12M  -0.40%

In [29]:
df.reset_index()

      公司         日期      收盘      开盘       高       低     交易量     涨跌幅
0   BABA  2023-4-10  101.54  100.62  102.83  100.59  16.26M  -1.17%
1   BABA  2023-4-11   99.76  102.46  102.54   99.20  18.10M  -1.75%
2   BABA  2023-4-12   93.84   97.82   98.89   93.58  33.81M  -5.93%
3   BABA  2023-4-13   96.17   95.88   97.19   95.10  23.22M   2.48%
4   BABA  2023-4-14   94.55   95.63   96.12   93.84  14.10M  -1.68%
..   ...        ...     ...     ...     ...     ...     ...     ...
71   PDD  2023-4-28   68.15   65.40   68.81   65.40   6.02M   3.07%
72   PDD   2023-4-3   74.84   74.07   74.89   72.20   7.27M  -1.40%
73   PDD   2023-4-4   73.20   74.90   74.90   72.79   5.00M  -2.19%
74   PDD   2023-4-5   72.32   73.14   73.14   71.62   5.24M  -1.20%
75   PDD   2023-4-6   72.03   72.50   72.60   71.16   5.12M  -0.40%

[76 rows x 8 columns]